// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BTpower

#ifndef _BTPOWER_UI_H
#define _BTPOWER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_Voltage(lv_event_t * e);
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_HighV;
extern lv_obj_t * ui_LowV;
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_Pressure;
extern lv_obj_t * ui_Pvalue;
void ui_event_Temperature(lv_event_t * e);
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_HighT;
extern lv_obj_t * ui_LowT;
extern lv_obj_t * ui_Altitude;
extern lv_obj_t * ui_Avalue;
void ui_event_Other(lv_event_t * e);
extern lv_obj_t * ui_Other;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_CQTY;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_RecordCount;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Version1;
extern lv_obj_t * ui_Version2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Banner;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_CO2Val;
extern lv_obj_t * ui_TVOCVal;
extern lv_obj_t * ui_CH20Val;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_TVOCBar;
extern lv_obj_t * ui_CO2Bar;
extern lv_obj_t * ui_CH20Bar;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_a2_png);    // assets/a2.png
LV_IMG_DECLARE(
    ui_img_baseline_bluetooth_connected_black_24dp_png);    // assets/baseline_bluetooth_connected_black_24dp.png
LV_IMG_DECLARE(ui_img_baseline_wifi_black_24dp_png);    // assets/baseline_wifi_black_24dp.png
LV_IMG_DECLARE(ui_img_wuko_png);    // assets/wuko.png

// FONTS
LV_FONT_DECLARE(ui_font_ClockFont);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_chinese_16);
LV_FONT_DECLARE(ui_font_chinese_20);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
