// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BTpower

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_water_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 頂部居中標題與版本容器 (車內空氣狀態監督站 v1.4.2)
    lv_obj_t * ui_Header2 = lv_obj_create(ui_Screen2);
    lv_obj_set_size(ui_Header2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(ui_Header2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Header2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Header2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_opa(ui_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Header2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Header2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(ui_Header2, LV_ALIGN_TOP_MID, 0, 2);

    ui_Banner = lv_label_create(ui_Header2);
    lv_obj_set_width(ui_Banner, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Banner, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Banner, "車內空氣狀態監督站");
    lv_obj_set_style_text_color(ui_Banner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Banner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Banner, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Version2 = lv_label_create(ui_Header2);
    lv_obj_set_width(ui_Version2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Version2, LV_SIZE_CONTENT);
    lv_label_set_text(ui_Version2, "v1.4.2");
    lv_obj_set_style_text_color(ui_Version2, lv_color_hex(0x64DDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Version2, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Version2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 2);
    lv_obj_set_y(ui_Label12, 35);
    lv_label_set_text(ui_Label12, "二氧化碳 (CO2)");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x02FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 2);
    lv_obj_set_y(ui_Label13, 115);
    lv_label_set_text(ui_Label13, "揮發有機物 (TVOC)");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x02FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 2);
    lv_obj_set_y(ui_Label14, 205);
    lv_label_set_text(ui_Label14, "甲醛濃度 (CH2O)");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x02FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Val = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_CO2Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Val, 0);
    lv_obj_set_y(ui_CO2Val, 72);
    lv_obj_set_align(ui_CO2Val, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_CO2Val, "386 ppm");
    lv_obj_set_style_text_color(ui_CO2Val, lv_color_hex(0xFAFA68), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2Val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2Val, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVOCVal = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TVOCVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVOCVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TVOCVal, 0);
    lv_obj_set_y(ui_TVOCVal, 10);
    lv_obj_set_align(ui_TVOCVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVOCVal, "0.001 mg/m3");
    lv_obj_set_style_text_color(ui_TVOCVal, lv_color_hex(0xFAFA68), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVOCVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TVOCVal, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH20Val = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_CH20Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CH20Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH20Val, 0);
    lv_obj_set_y(ui_CH20Val, -45);
    lv_obj_set_align(ui_CH20Val, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_CH20Val, "0.0004 mg/m3");
    lv_obj_set_style_text_color(ui_CH20Val, lv_color_hex(0xFAFA68), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CH20Val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CH20Val, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -4);
    lv_obj_set_y(ui_Label15, 60);
    lv_obj_set_align(ui_Label15, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label15, "上限: 15,000ppm");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -4);
    lv_obj_set_y(ui_Label16, 140);
    lv_obj_set_align(ui_Label16, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label16, "上限: 0.60mg/m3");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -4);
    lv_obj_set_y(ui_Label17, 230);
    lv_obj_set_align(ui_Label17, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label17, "上限: 0.15mg/m3");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVOCBar = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_TVOCBar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TVOCBar, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_TVOCBar, 19);
    lv_obj_set_width(ui_TVOCBar, lv_pct(25));
    lv_obj_set_x(ui_TVOCBar, 0);
    lv_obj_set_y(ui_TVOCBar, -15);
    lv_obj_set_align(ui_TVOCBar, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_style_bg_color(ui_TVOCBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVOCBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVOCBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVOCBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TVOCBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TVOCBar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CO2Bar = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_CO2Bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_CO2Bar, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_CO2Bar, 19);
    lv_obj_set_width(ui_CO2Bar, lv_pct(25));
    lv_obj_set_x(ui_CO2Bar, 10);
    lv_obj_set_y(ui_CO2Bar, -15);
    lv_obj_set_align(ui_CO2Bar, LV_ALIGN_BOTTOM_LEFT);

    lv_obj_set_style_bg_color(ui_CO2Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CO2Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CO2Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CO2Bar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CO2Bar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CH20Bar = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_CH20Bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_CH20Bar, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_CH20Bar, 19);
    lv_obj_set_width(ui_CH20Bar, lv_pct(25));
    lv_obj_set_x(ui_CH20Bar, -10);
    lv_obj_set_y(ui_CH20Bar, -15);
    lv_obj_set_align(ui_CH20Bar, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_set_style_bg_color(ui_CH20Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CH20Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CH20Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CH20Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CH20Bar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CH20Bar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // 頁面指示圓點 (○ ●)
    lv_obj_t * ui_Dot2_1 = lv_obj_create(ui_Screen2);
    lv_obj_set_size(ui_Dot2_1, 6, 6);
    lv_obj_set_style_radius(ui_Dot2_1, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dot2_1, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dot2_1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dot2_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_Dot2_1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_align(ui_Dot2_1, LV_ALIGN_BOTTOM_MID, -8, -5);

    lv_obj_t * ui_Dot2_2 = lv_obj_create(ui_Screen2);
    lv_obj_set_size(ui_Dot2_2, 6, 6);
    lv_obj_set_style_radius(ui_Dot2_2, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dot2_2, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dot2_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dot2_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_Dot2_2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_align(ui_Dot2_2, LV_ALIGN_BOTTOM_MID, 8, -5);

    // 全螢幕透明觸控覆蓋層：保證觸碰螢幕任何點（不論點在字體、數值、條狀圖或背景）都能切換畫面
    lv_obj_t * ui_TouchLayer2 = lv_obj_create(ui_Screen2);
    lv_obj_set_size(ui_TouchLayer2, lv_pct(100), lv_pct(100));
    lv_obj_set_align(ui_TouchLayer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TouchLayer2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_TouchLayer2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_opa(ui_TouchLayer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TouchLayer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_TouchLayer2, ui_event_Screen2, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
