// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BTpower

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_water_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Voltage = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Voltage, lv_pct(100));
    lv_obj_set_height(ui_Voltage, lv_pct(30));
    lv_obj_set_x(ui_Voltage, 0);
    lv_obj_set_y(ui_Voltage, 27);
    lv_obj_set_align(ui_Voltage, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Voltage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Voltage, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Voltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Voltage, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -20);
    lv_obj_set_y(ui_Label1, lv_pct(-8));
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "00.0V");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x02FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, lv_pct(0));
    lv_obj_set_y(ui_Label2, lv_pct(-18));
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "電池電壓");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF96969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighV = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_HighV, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighV, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighV, 1);
    lv_obj_set_y(ui_HighV, lv_pct(-6));
    lv_obj_set_align(ui_HighV, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HighV, "0.0V");
    lv_obj_set_style_text_color(ui_HighV, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowV = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_LowV, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowV, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowV, 1);
    lv_obj_set_y(ui_LowV, lv_pct(25));
    lv_obj_set_align(ui_LowV, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LowV, "0.0V");
    lv_obj_set_style_text_color(ui_LowV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_Wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi, 0);
    lv_obj_set_y(ui_Wifi, lv_pct(-8));
    lv_obj_set_align(ui_Wifi, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Wifi, "W");
    lv_obj_set_style_text_color(ui_Wifi, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pressure = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_Pressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Pressure, 8);
    lv_obj_set_x(ui_Pressure, lv_pct(-28));
    lv_obj_set_align(ui_Pressure, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Pressure, "大氣壓力:");
    lv_obj_set_style_text_color(ui_Pressure, lv_color_hex(0x36FE61), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pressure, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pvalue = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_Pvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pvalue, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Pvalue, 28);
    lv_obj_set_y(ui_Pvalue, 8);
    lv_obj_set_align(ui_Pvalue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Pvalue, "1004.94 hPa");
    lv_obj_set_style_text_color(ui_Pvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature, lv_pct(100));
    lv_obj_set_height(ui_Temperature, lv_pct(29));
    lv_obj_set_x(ui_Temperature, 0);
    lv_obj_set_y(ui_Temperature, lv_pct(40));
    lv_obj_set_align(ui_Temperature, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Temperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Temperature, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temperature, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Temperature, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -20);
    lv_obj_set_y(ui_Label3, lv_pct(-4));
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "00.0°C");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFAFA68), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, lv_pct(0));
    lv_obj_set_y(ui_Label4, lv_pct(-17));
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "電池溫度");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFB7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighT = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_HighT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighT, 1);
    lv_obj_set_y(ui_HighT, lv_pct(-6));
    lv_obj_set_align(ui_HighT, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HighT, "0.0°C");
    lv_obj_set_style_text_color(ui_HighT, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowT = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_LowT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowT, 1);
    lv_obj_set_y(ui_LowT, lv_pct(27));
    lv_obj_set_align(ui_LowT, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LowT, "0.0°C");
    lv_obj_set_style_text_color(ui_LowT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Altitude = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_Altitude, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Altitude, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Altitude, 8);
    lv_obj_set_x(ui_Altitude, lv_pct(-28));
    lv_obj_set_align(ui_Altitude, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Altitude, "海拔高度:");
    lv_obj_set_style_text_color(ui_Altitude, lv_color_hex(0xFFFE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Altitude, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Altitude, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Avalue = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_Avalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Avalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Avalue, 28);
    lv_obj_set_y(ui_Avalue, 8);
    lv_obj_set_align(ui_Avalue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Avalue, "68.91 m");
    lv_obj_set_style_text_color(ui_Avalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Avalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Avalue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Avalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Other = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Other, lv_pct(100));
    lv_obj_set_height(ui_Other, 92);
    lv_obj_set_x(ui_Other, 0);
    lv_obj_set_y(ui_Other, 218);
    lv_obj_set_align(ui_Other, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Other, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Other, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Other, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Other, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Other, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Other, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, lv_pct(0));
    lv_obj_set_y(ui_Label5, lv_pct(-12));
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "系統狀態");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF96969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, lv_pct(-5));
    lv_obj_set_y(ui_Label6, lv_pct(10));
    lv_label_set_text(ui_Label6, "無線遙測:");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label7, 8);
    lv_obj_set_x(ui_Label7, lv_pct(30));
    lv_label_set_text(ui_Label7, "IP");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x64DDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, lv_pct(-5));
    lv_obj_set_y(ui_Label8, lv_pct(40));
    lv_label_set_text(ui_Label8, "運行時間:");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label9, 28);
    lv_obj_set_x(ui_Label9, lv_pct(30));
    lv_label_set_text(ui_Label9, "00:00:00");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x64DDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, lv_pct(-5));
    lv_obj_set_y(ui_Label18, lv_pct(70));
    lv_label_set_text(ui_Label18, "封包:");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordCount = lv_label_create(ui_Other);
    lv_obj_set_width(ui_RecordCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordCount, lv_pct(16));
    lv_obj_set_y(ui_RecordCount, lv_pct(70));
    lv_label_set_text(ui_RecordCount, "0");
    lv_obj_set_style_text_color(ui_RecordCount, lv_color_hex(0x64DDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecordCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Other);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, lv_pct(46));
    lv_obj_set_y(ui_Label11, lv_pct(70));
    lv_label_set_text(ui_Label11, "連線數:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CQTY = lv_label_create(ui_Other);
    lv_obj_set_width(ui_CQTY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CQTY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CQTY, lv_pct(76));
    lv_obj_set_y(ui_CQTY, lv_pct(70));
    lv_label_set_text(ui_CQTY, "0");
    lv_obj_set_style_text_color(ui_CQTY, lv_color_hex(0x64DDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CQTY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 3);
    lv_obj_set_align(ui_Label10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label10, "電壓及車內空氣狀態監督站");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_chinese_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 全螢幕透明觸控覆蓋層：保證觸碰螢幕任何點（不論點在字體、數值、條狀圖或背景）都能切換畫面
    lv_obj_t * ui_TouchLayer1 = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_TouchLayer1, lv_pct(100), lv_pct(100));
    lv_obj_set_align(ui_TouchLayer1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TouchLayer1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_TouchLayer1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_opa(ui_TouchLayer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TouchLayer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_TouchLayer1, ui_event_Screen1, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Voltage, ui_event_Voltage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temperature, ui_event_Temperature, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Other, ui_event_Other, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
