// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: BTpower

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen2, &ui_img_water_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Banner = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Banner, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Banner, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Banner, 0);
    lv_obj_set_y(ui_Banner, 1);
    lv_obj_set_align(ui_Banner, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Banner, "Air Status");
    lv_obj_set_style_text_color(ui_Banner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Banner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Banner, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 2);
    lv_obj_set_y(ui_Label12, 30);
    lv_label_set_text(ui_Label12, "CO2");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x02FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 4);
    lv_obj_set_y(ui_Label13, 120);
    lv_label_set_text(ui_Label13, "TVOC");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x02FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 2);
    lv_obj_set_y(ui_Label14, 200);
    lv_label_set_text(ui_Label14, "CH20");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x02FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Val = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_CO2Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Val, 0);
    lv_obj_set_y(ui_CO2Val, 80);
    lv_obj_set_align(ui_CO2Val, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_CO2Val, "386 ppm");
    lv_obj_set_style_text_color(ui_CO2Val, lv_color_hex(0xFAFA68), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2Val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2Val, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVOCVal = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TVOCVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVOCVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TVOCVal, 0);
    lv_obj_set_y(ui_TVOCVal, 20);
    lv_obj_set_align(ui_TVOCVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVOCVal, "0.001 mg/m3");
    lv_obj_set_style_text_color(ui_TVOCVal, lv_color_hex(0xFAFA68), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVOCVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TVOCVal, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH20Val = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_CH20Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CH20Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH20Val, 0);
    lv_obj_set_y(ui_CH20Val, -45);
    lv_obj_set_align(ui_CH20Val, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_CH20Val, "0.0004 mg/m3");
    lv_obj_set_style_text_color(ui_CH20Val, lv_color_hex(0xFAFA68), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CH20Val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CH20Val, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 55);
    lv_obj_set_y(ui_Label15, -96);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "< 15,000ppm");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -4);
    lv_obj_set_y(ui_Label16, 150);
    lv_obj_set_align(ui_Label16, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label16, "< 0.60mg/m3");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 70);
    lv_obj_set_y(ui_Label17, 75);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "< 0.15 mg/m3");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVOCBar = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_TVOCBar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TVOCBar, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_TVOCBar, 19);
    lv_obj_set_width(ui_TVOCBar, lv_pct(25));
    lv_obj_set_x(ui_TVOCBar, 0);
    lv_obj_set_y(ui_TVOCBar, -15);
    lv_obj_set_align(ui_TVOCBar, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_style_bg_color(ui_TVOCBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVOCBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVOCBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVOCBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TVOCBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TVOCBar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CO2Bar = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_CO2Bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_CO2Bar, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_CO2Bar, 19);
    lv_obj_set_width(ui_CO2Bar, lv_pct(25));
    lv_obj_set_x(ui_CO2Bar, 10);
    lv_obj_set_y(ui_CO2Bar, -15);
    lv_obj_set_align(ui_CO2Bar, LV_ALIGN_BOTTOM_LEFT);

    lv_obj_set_style_bg_color(ui_CO2Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CO2Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CO2Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CO2Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CO2Bar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CO2Bar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CH20Bar = lv_bar_create(ui_Screen2);
    lv_bar_set_value(ui_CH20Bar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_CH20Bar, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_CH20Bar, 19);
    lv_obj_set_width(ui_CH20Bar, lv_pct(25));
    lv_obj_set_x(ui_CH20Bar, -10);
    lv_obj_set_y(ui_CH20Bar, -15);
    lv_obj_set_align(ui_CH20Bar, LV_ALIGN_BOTTOM_RIGHT);

    lv_obj_set_style_bg_color(ui_CH20Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CH20Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CH20Bar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CH20Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CH20Bar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CH20Bar, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
